CREATE TYPE "public"."complaint_category" AS ENUM('academic', 'infrastructure', 'hostel', 'transport', 'ragging', 'other');--> statement-breakpoint
CREATE TYPE "public"."complaint_priority" AS ENUM('low', 'medium', 'high', 'urgent');--> statement-breakpoint
CREATE TYPE "public"."complaint_status" AS ENUM('pending', 'in_progress', 'resolved', 'rejected');--> statement-breakpoint
CREATE TABLE "complain_ease_complaint" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "complain_ease_complaint_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL,
	"description" text NOT NULL,
	"category" "complaint_category" NOT NULL,
	"priority" "complaint_priority" DEFAULT 'medium' NOT NULL,
	"status" "complaint_status" DEFAULT 'pending' NOT NULL,
	"mediaUrl" varchar(1024),
	"filedBy" varchar(256) NOT NULL,
	"filedAt" timestamp with time zone NOT NULL,
	"resolvedAt" timestamp with time zone,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "category_idx" ON "complain_ease_complaint" USING btree ("category");--> statement-breakpoint
CREATE INDEX "status_idx" ON "complain_ease_complaint" USING btree ("status");--> statement-breakpoint
CREATE INDEX "filed_by_idx" ON "complain_ease_complaint" USING btree ("filedBy");